Add configuration
bonilab/PSU-CIDD-MaSim-Support pull request #13
Opened 2021-03-05 19:06 UTC by PakhiAgarwal

2021-03-05 19:06 UTC, pep8speaks commented
Hello @PakhiAgarwal! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`loader.py`](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py):

> [Line 35:14](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L35): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 49:66](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L49): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 52:121](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L52): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 55:38](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L55): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 55:62](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L55): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 64:34](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L64): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 72:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L72): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 72:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L72): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 73:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L73): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 75:42](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L75): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 75:67](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L75): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 97:66](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L97): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 100:121](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 103:38](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L103): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 103:62](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L103): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 112:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L112): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 123:40](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L123): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 132:32](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L132): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 149:48](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L149): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 165:32](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L165): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 165:40](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L165): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 171:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L171): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 177:58](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L177): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 195:34](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L195): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 198:65](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L198): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 209:32](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L209): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 212:44](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L212): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 216:55](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L216): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 219:121](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 235:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L235): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 241:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L241): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 248:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L248): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 254:1](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L254): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 256:14](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L256): [E211](https://duckduckgo.com/?q=pep8%20E211) whitespace before '('
> [Line 258:14](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L258): [E211](https://duckduckgo.com/?q=pep8%20E211) whitespace before '('
> [Line 259:14](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L259): [E211](https://duckduckgo.com/?q=pep8%20E211) whitespace before '('
> [Line 263:34](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loader.py#L263): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 266:55](https://github.com/bonilab/PSU-CIDD-MaSim-Support/blob/22485c2b212a4c0aebaf0edbae73487038e5a78f/loade [...]

2021-03-08 16:44 UTC, rjzupkoii requested changes
Looks like the script needs to be updated to Python3 which should be straightforward. I suspect that some testing of the script is still needed, so take a closer look at that. Also, be sure to clear all of the items that the PEP8 script is mentioning.

2021-03-08 16:44 UTC, rjzupkoii commented on loader.py
>      studyId = int(sys.argv[1])
Make sure you are testing the scripts, both of these variables are referring to the same index number.

2021-03-08 16:44 UTC, rjzupkoii commented on loader.py
>      if len(sys.argv) != 3:
This value needs to be updated to match the number of parameters.

2021-03-09 17:59 UTC, PakhiAgarwal commented
@rjzupkoii I have resolved PEP8 conflicts and updated the script to Python3. Please let me know if it looks okay now.

2021-03-09 18:50 UTC, rjzupkoii requested changes

2021-03-09 18:50 UTC, rjzupkoii commented on loader.py
> +    return select(sql, {'replicateId': replicateId, 'startDay': startDay})
Looks like the signature for the `select` functions still haven't been updated?

2021-03-09 18:55 UTC, rjzupkoii commented
Try using this command line when testing the loader script, you may need to pull the Rwanda repository (https://github.com/rjzupkoii/PSU-CIDD-Rwanda):

`loader.py rwa-configuration.yml 2 4015`

2021-03-09 19:21 UTC, PakhiAgarwal commented
> Try using this command line when testing the loader script, you may need to pull the Rwanda repository (https://github.com/rjzupkoii/PSU-CIDD-Rwanda):
> 
> `loader.py rwa-configuration.yml 2 4015`

I cannot find `rwa-configuration.yml`.
Also in the current MaSim repo there is no yml file. Have you removed them from here?

2021-03-09 19:44 UTC, PakhiAgarwal commented
Surprisingly, I am not getting any errors while running from Pycharm, but from terminal, there are a few errors.

2021-03-09 19:45 UTC, PakhiAgarwal commented
> > Try using this command line when testing the loader script, you may need to pull the Rwanda repository (https://github.com/rjzupkoii/PSU-CIDD-Rwanda):
> > `loader.py rwa-configuration.yml 2 4015`
> 
> I cannot find `rwa-configuration.yml`.
> Also in the current MaSim repo there is no yml file. Have you removed them from here?

I found the file.

2021-03-09 21:55 UTC, PakhiAgarwal commented
> Try using this command line when testing the loader script, you may need to pull the Rwanda repository (https://github.com/rjzupkoii/PSU-CIDD-Rwanda):
> 
> `loader.py rwa-configuration.yml 2 4015`

@rjzupkoii While running with these values, I am getting this error:
`TypeError: Expected bytes or unicode string, got dict instead`
Is it related to `psycopg`?

2021-03-10 01:28 UTC, rjzupkoii commented
@PakhiAgarwal It's most likely related to the file access, try `with open(filename, "w") as csvfile:` instead.

2021-03-10 01:56 UTC, PakhiAgarwal commented
> with open(filename, "w") as csvfile:

I tried this but its the same, I think the error is in this line `return select(connection, sql, {'studyId': studyId})`
The error is `TypeError: Expected bytes or unicode string, got dict instead`, I think it refers to `{'studyId': studyId})`
I am not sure what changes are required here.

2021-03-10 02:13 UTC, rjzupkoii commented
@PakhiAgarwal Is there a stack trace being returned by Python that you can post?

2021-03-10 02:20 UTC, PakhiAgarwal commented
> @PakhiAgarwal Is there a stack trace being returned by Python that you can post?

![error_8](https://user-images.githubusercontent.com/20890066/110565896-3b11f780-811d-11eb-80af-405a138d0ab5.JPG)

2021-03-10 14:21 UTC, rjzupkoii commented
@PakhiAgarwal You're passing in the entire configuration when you should just be passing the connection string to the function.

2021-03-10 15:11 UTC, PakhiAgarwal commented
> @PakhiAgarwal You're passing in the entire configuration when you should just be passing the connection string to the function.

Thanks. Got it. Now I am getting connection time out error. 
` Is the server running on host "masimdb.vmhost.psu.edu" (128.118.15.151) and accepting
        TCP/IP connections on port 5432?`

2021-03-10 15:32 UTC, PakhiAgarwal commented
Now, I am having this:

replicates = get_replicates(study[0], study[1])
TypeError: get_replicates() missing 1 required positional argument: 'label'

What does 'label' signify in get_replicates() and what argument am I supposed to provide here?

2021-03-10 15:54 UTC, PakhiAgarwal commented
@rjzupkoii I had made changes. Please have a look. The script is working now.

2021-03-10 16:19 UTC, merged